---

- hosts: all

  roles: 

  - role: marvel-nccr.simulationbase
    tags: [simulationbase]
    vars:
      simulationbase_vm_user: "{{ vm_user }}"
      simulationbase_hostname: "{{ vm_hostname }}"
      simulationbase_codes_folder: "{{ vm_codes_folder }}"
      simulationbase_tmz: Europe/Zurich

  - role: marvel-nccr.quantum_espresso
    tags: [quantum_espresso]
    vars:
      quantum_espresso_data_folder: "{{ vm_data_folder }}"
      quantum_espresso_version: "7.0"

  - role: mse468.gulp
    tags: [gulp]
    vars:
      gulp_code_folder: "{{ vm_codes_folder }}"

  - role: marvel-nccr.ubuntu_desktop
    tags: [ubuntu_desktop]
    vars:
      ubuntu_desktop_browser: "{{ vm_browser }}"
      ubuntu_desktop_vm_user: "{{ vm_user }}"
    when: not vm_headless

  - role: marvel-nccr.quantum_mobile_customizations
    tags: [qm_customizations]
    vars:
      qm_customizations_browser: "{{ vm_browser }}"
      qm_customizations_vm_user: "{{ vm_user }}"
      qm_customizations_vm_password: "{{ vm_password }}"
      qm_customizations_vm_name: "{{ vm_name }}"
      qm_customizations_vm_version: "{{ vm_version }}"
      qm_customizations_vm_author: "{{ vm_author }}"
      qm_customizations_headless: "{{ vm_headless }}"
      qm_customizations_examples_folder: "{{ vm_examples_folder }}"
      qm_customizations_examples_readme: "{{ vm_examples_folder_reamde }}"
      qm_customizations_data_folder: "{{ vm_data_folder }}"
      qm_customizations_readme_file: "{{ vm_readme_file }}"
      qm_customizations_homepage: "https://quantum-mobile.readthedocs.io"
      qm_customizations_urls:
        Abinit: https://www.abinit.org
        BigDFT: http://www.bigdft.org
        CP2K: https://www.cp2k.org
        Fleur: http://www.flapw.de/
        NWChem: https://nwchemgit.github.io/
        Quantum ESPRESSO: http://www.quantum-espresso.org/
        Siesta: https://gitlab.com/siesta-project/siesta
        Wannier90: http://www.wannier.org
        Yambo: http://www.yambo-code.org/

  - role: marvel-nccr.editors
    tags: [editors]
    vars:
      editors_vm_user: "{{ vm_user }}"


  post_tasks:

  # the following tasks should only be run after the machine is fully provisioned
  # since these tasks break idempotence

  - name: apt-get clean  # noqa 303
    tags: [never, cleanup]
    become: true
    command: apt-get clean

  - name: wipe apt lists
    tags: [never, cleanup]
    become: true
    command: "rm -rf /var/lib/apt/lists/*"  # noqa 302

  - name: wipe user cache
    tags: [never, cleanup]
    become: true
    become_user: "{{ vm_user }}"
    file:
      state: absent
      path: "~/.cache"

  - name: wipe root user cache
    tags: [never, cleanup]
    become: true
    file:
      state: absent
      path: "~/.cache"