- name: Create man directory
  when: cloud_platform == 'docker'
  file:
    path: /usr/share/man/man1
    state: directory

- name: Install plotting tools, etc.
  become: true
  apt:
    name:
    # For plotting
    - grace
    - gnuplot
    - xcrysden
    # note: jmol+java = 110MB
    - jmol
    - default-jre
    state: present

- include_role:
    name: release_notes
  vars:
    section: "Plotting Tools"
    option: "available tools"
    value: "xmgrace, gnuplot, xcrysden, jmol"
  when: release_notes is defined and release_notes
